### ISSUE TITLE
请问方便加入猪(Sus scrofa)的index么？

### ISSUE THREAD

**Issue by ggfengxuan** [Genetalks/gtz#10]
之前用gtz压缩过20T的猪的数据，压缩率为16%(gz为28%)，想体验下现在的高倍压缩模式，不知道贵团队方便添加下猪的index么？谢谢！
猪的基因组下载地址如下：
ftp://ftp.ensembl.org/pub/release-94/fasta/sus_scrofa/dna/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa.gz

**Comment by superligen** [comment]
应您的请求，我们已经着手添加猪参考基因组数据，待测试完毕后，我们会在这留言通知您。敬请期待。

**Comment by ggfengxuan** [comment]
> 应您的请求，我们已经着手添加猪参考基因组数据，待测试完毕后，我们会在这留言通知您。敬请期待。

非常感谢！

**Comment by zhaolx01** [comment]
您好，我们已将Sus scrofa添加进gtz_index的参考基因组制作列表，制作编号为36，您需要运行“gtz_index"，在交互中输入需要制作的物种标号”36“，并选择参考基因组保存路径。制作完成将生成如下3个文件支持您对Sus scrofa数据的加解压：

> Sus_scrofa_fa17a95f7b8532dfb932210977bebc77.bin
> Sus_scrofa_fa17a95f7b8532dfb932210977bebc77.rbin
> Sus_scrofa_fa17a95f7b8532dfb932210977bebc77.rec

**Comment by ggfengxuan** [comment]
> 您好，我们已将Sus scrofa添加进gtz_index的参考基因组制作列表，制作编号为36，您需要运行“gtz_index"，在交互中输入需要制作的物种标号”36“，并选择参考基因组保存路径。制作完成将生成如下3个文件支持您对Sus scrofa数据的加解压：
> 
> > Sus_scrofa_fa17a95f7b8532dfb932210977bebc77.bin
> > Sus_scrofa_fa17a95f7b8532dfb932210977bebc77.rbin
> > Sus_scrofa_fa17a95f7b8532dfb932210977bebc77.rec

收到，谢谢！
