### ISSUE TITLE
gtz v1.2.2 bin模式压缩 验证出现假死

### ISSUE THREAD

**Issue by flyingdancen** [Genetalks/gtz#11]
你好，目前在使用gtz压缩原始数据，在压缩小麦的数据，压缩完验证文件的时候，会偶尔出现（目前只在v1.2.2发现，出现2次了）停在验证这一步，top看进程发现gtz一直在运行，但是验证这一步超过1700min...只能手动kill掉进程。
目前还不能确定是什么问题，因为重新压缩一次的时候又通过了，这里只提交碰到的问题吧

**Comment by zhaolx01** [comment]
您好，校验的过程需要rbin参考序列文件，默认会在”~/.config/gtz/"和压缩命令中’-b'指定参考序列的同一路径查找，若都没有会自动下载然后进行校验。按您所诉，应该是耗费了时间去自动下载rbin参考序列文件”Triticum_aestivum_8e2da4d2c18d5fadd1d3cd0c15e918d0.rbin“。如果需要使用校验功能，建议按前文所诉配置好rbin参考序列文件，若想关闭校验功能可使用"-n"参数。
   我们建有GTX.Zip交流群（QQ群：934492381，微信群请回看gtz下载页二维码），欢迎您的加入

**Comment by flyingdancen** [comment]
谢谢你的解答，但我觉得并不是这个原因，我的bin文件和rbin文件是放在同一个目录下的，而且我的”~/.config/gtz/"是空目录，当时为了不自动查询bin文件特意设成空目录的，经你所说现在检查还是空目录。

**Comment by flyingdancen** [comment]
反馈信息提供不了。。因为是放在perl里面跑的，我自己设置重复运行第3次时返回第三次的信息，但是第一次就卡住我就没办法了。
perl里面的命令：
$msg = `$gtz $file -f -e -p $threads -o $out -b $bin`;
这里卡在验证，kill掉对应进程后源文件还保留着。

gtz WGC101998-BN27_combined_R1.fastq.gz -o aa.gtz -p 8 -b /Bio/User/liuyubin/software/gtz/gtz_config/Triticum_aestivum_8e2da4d2c18d5fadd1d3cd0c15e918d0.bin
这是在当前目录手动跑的，没加参数-f和-e，正常运行结束了
