### ISSUE TITLE
同一个物种不同版本的基因组，需要建立相应的index吗？

### ISSUE THREAD

**Issue by Lizd0630** [Genetalks/gtz#12]
同一个物种不同版本的基因组如小鼠的mm9，mm10，需要建立相应的index压缩和解压相应的文件吗？不同版本的基因组fasta文件不一样，怎么在不同版本之间转换？

**Comment by bolunfeng** [comment]
您好！非常感谢您使用GTX.Zip。首先，建立index文件，只需要与所属物种的基因组相对应就可以，不需要细分到基因组的版本这个层级上。其次，为了数据的最终安全，所有用于建立index的原始rbin，都是由我们制作生成，并发布给用户使用的。比如您有其它物种，不在我们目前支持的物种列表中，可以将fasta的下载链接提供给我们，由我们生成好这个物种的原始rbin文件，再供您来建立相应的bin和rbin文件。

**Comment by Lizd0630** [comment]
谢谢您的回复！
祝好！




--

Yours，
sincerely，Li Zhidan.

在 2019-01-08 17:36:26，"bolunfeng" <notifications@github.com> 写道：


您好！非常感谢您使用GTX.Zip。首先，建立index文件，只需要与所属物种的基因组相对应就可以，不需要细分到基因组的版本这个层级上。其次，为了数据的最终安全，所有用于建立index的原始rbin，都是由我们制作生成，并发布给用户使用的。比如您有其它物种，不在我们目前支持的物种列表中，可以将fasta的下载链接提供给我们，由我们生成好这个物种的原始rbin文件，再供您来建立相应的bin和rbin文件。
