### ISSUE TITLE
STAR with gtz is not working

### ISSUE THREAD

**Issue by sohnjangil** [Genetalks/gtz#13]
According to README file in gtz, STAR should be working with gtz compressed files, but it actually not.

We have downloaded last versions of gtz, and compressed a pair of RNA-seq as follows,
$ gtz RNAseq_R1.fastq.gz -o RNAseq_R1.fastq.gz.gtz
$ gtz RNAseq_R2.fastq.gz -o RNAseq_R2.fastq.gz.gtz
without reference.

Then we tried to use STAR directly with command
$ STAR --genomeDir /path/to/star_index --readFilesIn RNAseq_R1.fastq.gz.gtz RNAseq_R2.fastq.gz.gtz   --readFilesCommand gtz -r
But it was not working.
So, we would like to know which version of STAR is required for gtz compressed files.

-- Jang-il Sohn

**Comment by xuxiali13** [comment]
@sohnjangil , 
Hi, It looks like there's a problem with your command line, you didn't use refrence file to compress, so command line should as follows:

### First step:
STAR --runMode genomeGenerate --genomeDir /path/to/genomeDir --genomeFastaFiles /path/xxx.fasta

Did you do this step?

### Second Step:
STAR --genomeDir /path/to/genomeDir --readFilesIn read1.fq.gtz read2.fq.gtz --readFilesCommand gtz -c -d

Please try again, thank you. If you have any questions, welcome feedback.

In addition, our star version is: STAR_2.6.1d, and I updated GTZ's documentation on the star chapter.

**Comment by sohnjangil** [comment]
Thank you xuxiali13.

We already indexed genome, and working fine with normal fastq files, but it still not wokring with gtz compressed files.
The log files are...

$ /export/home/jang/Programs/STAR-2.7.0d/source/STAR --genomeDir ./star --readFilesIn RNAseq_R1.fastq.fg.gtz RNAseq_R2.fastq.fg.gtz --readFilesCommand gtz -c -d
./_STARtmp//readsCommand_read1: line 3: gtz: command not found
Feb 25 16:11:47 ..... started STAR run
Feb 25 16:11:47 ..... loading genome
./_STARtmp//readsCommand_read2: line 3: gtz: command not found

EXITING because of FATAL ERROR: Genome version: 20201 is INCOMPATIBLE with running STAR version: 2.7.0d
SOLUTION: please re-generate genome from scratch with running version of STAR, or with version: 2.7.0d

Feb 25 16:11:47 ...... FATAL ERROR, exiting

We used STAR-2.7.0d, but looks not supporing gtz.
Can you let me know what I should do to make STAR to support gtz files?
Is there any additional step in compiling STAR?

**Comment by sohnjangil** [comment]
I matched STAR versions of index file, but still not working and it gave error messages,
    ./_STARtmp//readsCommand_read1: line 3: gtz: command not found
   ./_STARtmp//readsCommand_read2: line 3: gtz: command not found
and the output sam file is empty.

--- Jang-il Sohn

**Comment by xuxiali13** [comment]
@sohnjangil ,

**Comment by xuxiali13** [comment]
@sohnjangil,
Hi, I test STAR 2.7.0d_0221 with GTZ, and it also work fine with gtz files.
It looks like GTZ is not installed in your environment, you execute `gtz -v` in the shell，can it display version information GTZ 1.2.3?
If gtz is not installed as a root user, after the first installation, you need to perform a source ~/.bashrc or exit to log back in. 
If there are still any problems, welcome feedback.

**Comment by sohnjangil** [comment]
Hi.
I cannot understand why it is not working on my system.
It is still not working.

In my system, gtz is not install as a root user.
So, following your comments, I performed source ~/.bashrc, but it is still not working.
Then, I tried after re-log, and also not working.

$ ~/Programs/STAR-2.7.0d/source/STAR --genomeDir ./star --readFilesIn RNAseq_R1.fastq.fg.gtz RNAseq_R2.fastq.fg.gtz --readFilesCommand gtz -c -d
./_STARtmp//readsCommand_read1: line 3: gtz: command not found
./_STARtmp//readsCommand_read2: line 3: gtz: command not found
Feb 26 19:11:56 ..... started STAR run
Feb 26 19:11:56 ..... loading genome
Feb 26 19:12:34 ..... started mapping
Feb 26 19:12:34 ..... finished mapping
Feb 26 19:12:38 ..... finished successfully

As you can see the error message, my STAR aligner is still not support gtz format.
In this case output file is Aligned.out.sam, but it contains nothing.

$ ls -lh Aligned.out.sam
-rw-rw-r-- 1 jang jang    0 Feb 26 19:16 Aligned.out.sam

STAR should be installed after installation of gtz? After source ~/.bashrc?

**Comment by sohnjangil** [comment]
Finally, I found it.
It works with absolute path of gtz.

After modifying
--readFilesCommand gtz
to
--readFilesCommand /home/jang/.config/GTZ/gtz
then it works!

Thank you!
