### ISSUE TITLE
fastqc-gtz couldn't be installed without root permission

### ISSUE THREAD

**Issue by chaoscicada** [Genetalks/gtz#14]
I tried to install fastqc-gtz on our school's cluster, since I don't have the root permission, I need to install it in my home dir, but it got the error.

![20190315193603](https://user-images.githubusercontent.com/18159914/54428929-04858a00-475a-11e9-94ff-62e7ee760ae9.png)

**Comment by bolunfeng** [comment]
Thank you very much for your feedback.we will fix it as soon as possible.We will notify you in a timely manner.

**Comment by bolunfeng** [comment]
Hello. The installation package of  has been updated.
