### ISSUE TITLE
broken pipe issue 

### ISSUE THREAD

**Issue by mellowo** [Genetalks/gtz#18]
hi
I'm testing the gtz program.

During running the program, a failure occurred due to a brken pipe.

bwa-gtz mem -t 12 -M -R "@RG\tPL:Illumina\tID:A00552\tSM:NA12878\tLB:NA12878" genome.fa NA12878_R1.fastq.gtz NA12878_R2.fastq.gtz | samtools view -bSu - | samtools sort -@ 22 -m 8G - /gtz_test/NA12878_gtz_for_bwa_use_ref_Thead12.sorted

The fault log is as follows.

M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (22, 336272, 211, 7)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (177, 235, 305)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 561)
[M::mem_pestat] mean and std.dev: (246.27, 108.03)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 689)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (335, 386, 447)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (111, 671)
[M::mem_pestat] mean and std.dev: (392.79, 84.98)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 783)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (18, 37, 70)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 174)
[M::mem_pestat] mean and std.dev: (45.20, 36.32)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 226)
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_process_seqs] Processed 794702 reads in 386.185 CPU sec, 31.998 real sec
qsub_script_noSGE.sh: line 7: 46647 Done(141)               bwa-gtz mem -t 12 -M -R "@RG\tPL:Illumina\tID:A00552\tSM:NA12878\tLB:NA12878" genome.fa NA12878_R1.fastq.gtz NA12878_R2.fastq.gtz
     46648 Broken pipe             | samtools view -bSu -
     46649 Killed                  | samtools sort -@ 22 -m 8G - /gtz_test/NA12878_gtz_for_bwa_use_ref_nosge_Thead1.sorted

If you know how to solve it, I would appreciate it if you let me know.

**Comment by xuxiali13** [comment]
@mellowo 

Hi, mellowo,
I test my data in the local environment, and it works normally. I do not have the corresponding software version (samtools, GTZ) to yours, so I can only try to do the following analysis:

From the log analysis, bwa-gtz only have read the data once and reported the error, possible reasons:

#### 1.The data is corrupted
Here reads 794702 reads, not an integer of 4, it should be an integer of 4?
[M::mem_process_seqs] Processed 794702 reads in 386.185 CPU sec, 31.998 real sec

#### 2.The server may not have enough memory
You can help do as following:
-------------------------------------------------------------------
at first, make sure you have enough memory

#### 1. Use gtz to decompress NA12878_R1.fastq.gtz and NA12878_R2.fastq.gtz, and compare with the original file to see wether md5 is consistent
   by this test, we can know wether NA12878_R1.fastq.gtz and NA12878_R2.fastq.gtz are corrupted

#### 2. Run as same command args, but use bwa, and read NA12878_R1.fastq and NA12878_R2.fastq directly
   by this test, we can know wether the command is ok, and bwa-gtz is ok

#### 3. Run as same command args, Use bwa-gtz to read NA12878_R1.fastq and NA12878_R2.fastq

   by this test, we can know wether bwa-gtz work with NA12878_R1.fastq and NA12878_R2.fastq, but not for NA12878_R1.fastq.gtz and NA12878_R2.fastq.gtz

If steps 1, 2 and 3 are all normal, please send the corresponding fastq and fa to me, and tell me the samtools version and the GTZ of generating NA12878_R1.fastq.gtz and NA12878_R2.fastq.gtz. I will reproduce and analyze the problem again. 

Thank you!

**Comment by mellowo** [comment]
> @mellowo
> 
> Hi, mellowo,
> I test my data in the local environment, and it works normally. I do not have the corresponding software version (samtools, GTZ) to yours, so I can only try to do the following analysis:
> 
> From the log analysis, bwa-gtz only have read the data once and reported the error, possible reasons:
> 
> #### 1.The data is corrupted
> Here reads 794702 reads, not an integer of 4, it should be an integer of 4?
> [M::mem_process_seqs] Processed 794702 reads in 386.185 CPU sec, 31.998 real sec
> 
> #### 2.The server may not have enough memory
> ## You can help do as following:
> at first, make sure you have enough memory
> 
> #### 1. Use gtz to decompress NA12878_R1.fastq.gtz and NA12878_R2.fastq.gtz, and compare with the original file to see wether md5 is consistent
> by this test, we can know wether NA12878_R1.fastq.gtz and NA12878_R2.fastq.gtz are corrupted
> 
> #### 2. Run as same command args, but use bwa, and read NA12878_R1.fastq and NA12878_R2.fastq directly
> by this test, we can know wether the command is ok, and bwa-gtz is ok
> 
> #### 3. Run as same command args, Use bwa-gtz to read NA12878_R1.fastq and NA12878_R2.fastq
> by this test, we can know wether bwa-gtz work with NA12878_R1.fastq and NA12878_R2.fastq, but not for NA12878_R1.fastq.gtz and NA12878_R2.fastq.gtz
> 
> If steps 1, 2 and 3 are all normal, please send the corresponding fastq and fa to me, and tell me the samtools version and the GTZ of generating NA12878_R1.fastq.gtz and NA12878_R2.fastq.gtz. I will reproduce and analyze the problem again.
> 
> Thank you!

**Comment by mellowo** [comment]
Thank you for your quick reply.

In the topic "You can help do as following",

First, it was confirmed that the value of md5 is the same.

second, the program was performed normally in normal bwa. (NA12878.fastq.gz)

---------------------------------------------------------------------------------------------

What I am curious about is,

"Here reads 794702 reads, not an elementary of 4, it should be an elementary of 4?"
In the part, should the factor value of the -t option be given to 4 in the bwa-gtz mem option?

I did it by giving 12.

**Comment by xuxiali13** [comment]
please help do step3, because the version of bwa you use maybe not same as bwa-gtz. if bwa-gtz cann't work with NA12878_R1.fastq and NA12878_R2.fastq in step3, it's maybe the issue of corresponding version bwa in bwa-gtz. 
If steps 3 work normal, please send the corresponding fastq and fa to me, and tell me the samtools version and the GTZ of generating NA12878_R1.fastq.gtz and NA12878_R2.fastq.gtz. I will reproduce and analyze the problem again. 
thanks.

**Comment by mellowo** [comment]
The typical bwa version I used is 0.7.17,  i.e. the same version as bwa-gtz.

I will do test number 3 and write again. Thank you very much.

**Comment by mellowo** [comment]
Hi! As you said, I did test 3 times and it was done well! I have two servers, one where the program performed well and the other had an error, which is probably server specific failure. Maybe there was a problem with the computer I use. Thank you for taking care of my problem.

**Comment by xuxiali13** [comment]
you're welcome! If you have any questions or suggestions, please send an email to gen.li@genetalks.com, thanks.
