### ISSUE TITLE
GTZ stuck on .bam file after 72%

### ISSUE THREAD

**Issue by tal-franji-immunai** [Genetalks/gtz#24]
gtz get stuck , retried several times? Am I doing something wrong?
Here are the details:

I ran the following command
**$ nohup /home/XX/.config/GTZ/gtz possorted_genome_bam.bam --ref ../ref/cellranger_custom_hg38_ref_with_full_car_and_5utr.tar.gz &**

It got stuck after increasing precents with this messages (taking from the nohup.out file)

**first time use this Fasta, need convert it to binary... 72%**

I have tried to delete the output .gtz file and start again several times - but it still stuck
This is how the working directory looks like

**XX@HH:/mnt/disks/sdb/bamfile$ ls -l** 
total 273824532
-rw------- 1 XX XX      1840055 Jul 15 19:54 nohup.out
-rw-r--r-- 1 XX XX 280394439771 May 19 00:20 possorted_genome_bam.bam
-rw-rw-r-- 1 XX XX          108 Jul 15 19:45 possorted_genome_bam.bam.gtz
XX@HH:/mnt/disks/sdb/bamfile$ ls -l ../ref 
total 11120380
-rw-rw-r-- 1 XX XX 11387261138 Jul 15 07:50 cellranger_custom_hg38_ref_with_full_car_and_5utr.tar.gz

**Comment by xuxiali13** [comment]
@tal-franji-immunai , 

I'm sorry to reply to you so late. I have no "cellranger_custom_hg38_ref_with_full_car_and_5utr.tar.gz", so need you help to comfirm or do some test:

1. The gzfile "cellranger_custom_hg38_ref_with_full_car_and_5utr.tar.gz" is'not corrupted, it's ok when use gzip to unzip it?
2. If gzfile unzip normal, you can use --ref to spec the unziped file to compress bam.
3. You can help to test use "cellranger_custom_hg38_ref_with_full_car_and_5utr.tar.gz" to compress any one FASTQ(not bam), test gtz whether work normal, e.g. "gtz sample.fq --ref cellranger_custom_hg38_ref_with_full_car_and_5utr.tar.gz". this test will help me to analysis what happened.
4. Another question, Is your test on a distributed file system? If so, try the local disk. and which GTZ version?

I hope my answer will be helpful to you. If not helped, I wonder whether you are convenient to provide "cellranger_custom_hg38_ref_with_full_car_and_5utr.tar.gz" to me?

**Comment by superligen** [comment]
closed
