### ISSUE TITLE
Can I use it in cpu based on powerPC?

### ISSUE THREAD

**Issue by mellowo** [Genetalks/gtz#25]
I have a ppc64le based cpu. Does the source file or compiled executable available in ppc64le exist?

**Comment by superligen** [comment]
Hi,
Sorry, GTZ uses a lot of AVX instructions, which makes it difficult to port. We may not offer a platform porting version of ppc in the future. 
    One possible way around this is to try to perform binary translation from x86-64 to ppc using QEMU, but we haven't tried it ourselves.
    Thank you.
    Regards,
Gen Li, Genetalks



------------------------------------------------------------------
发件人：mellowo <notifications@github.com>
发送时间：2020年9月14日(星期一) 14:30
收件人：Genetalks/gtz <gtz@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[Genetalks/gtz] Can I use it in cpu based on powerPC? (#25)

I have a ppc64le based cpu. Does the source file or compiled executable available in ppc64le exist?

**Comment by mellowo** [comment]
I'll run it on QEMU.
Thank you for your quick reply.
