### ISSUE TITLE
生态软件技术提问

### ISSUE THREAD

**Issue by flystar233** [Genetalks/gtz#28]
您好，我想咨询下gtz与其生态软件匹配的问题。

我的猜测：
在如 bwa、tophat 这些软件的源码中，修改参数，使之当解析原始数据为gtz格式时，先对原始数据进行解压。解压后，数据成为原原软件可以接受的fastq（gz）格式。
还是有其他部分的修改？
谢谢~

**Comment by superligen** [comment]
您的猜测没错，大部分软件仅只是对了一下接口，让他们可以读取 gtz格式里的fastq数据。
但BWA-opt版本进行了一些小幅优化。


------------------------------------------------------------------
发件人：Xfly <notifications@github.com>
发送时间：2020年12月15日(星期二) 15:00
收件人：Genetalks/gtz <gtz@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[Genetalks/gtz] 生态软件技术提问 (#28)

您好，我想咨询下gtz与其生态软件匹配的问题。
我的猜测：
 在如 bwa、tophat 这些软件的源码中，修改参数，使之当解析原始数据为gtz格式时，先对原始数据进行解压。解压后，数据成为原原软件可以接受的fastq（gz）格式。
 还是有其他部分的修改？
 谢谢~

**Comment by superligen** [comment]
closed
