### ISSUE TITLE
'gtz -c' doesn't work

### ISSUE THREAD

**Issue by piroonj** [Genetalks/gtz#29]
Hi 
I have tried 'gtz file.gz -c' and I got output as file (file.gz.gtz). Indeed, the gtz program should print in stdout. Would you like to investigate this issue?
I used gtz  version: PROFESSIONAL-3.0.0-V-2020-12-09 01:58:41.

Best regards,
Piroon

**Comment by superligen** [comment]
Hi Piroon,
 Technically, GTZ files are designed to support high-speed data writes, and the file structure is defined to allow parallel read and write, much like a file in HDF5 format, which makes the write process requires seek operations and therefore does not support stdout.
 Thank you for your feedback on this issue, but unfortunately this feature is not possible at this time. 
     But decompression can be output to stdout. ( gtz -c -d ....)
 @徐霞丽Any additional comments?
Gen


------------------------------------------------------------------
发件人：piroonj <notifications@github.com>
发送时间：2021年1月13日(星期三) 16:23
收件人：Genetalks/gtz <gtz@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[Genetalks/gtz] 'gtz -c' doesn't work (#29)

Hi
 I have tried 'gtz file.gz -c' and I got output as file (file.gz.gtz). Indeed, the gtz program should print in stdout. Would you like to investigate this issue?
 I used gtz version: PROFESSIONAL-3.0.0-V-2020-12-09 01:58:41.
Best regards,
 Piroon

**Comment by piroonj** [comment]
Thank you for your quick response. 
I see.  
Best,
Piroon
