### ISSUE TITLE
Permitted to create Bioconda recipe?

### ISSUE THREAD

**Issue by tizzir** [Genetalks/gtz#4]
Hello, I'm interested in creating a Bioconda recipe for GTZ, but I can't quite tell if the license permits this.

I noticed the license is very similar to a BSD-2 license, just without the permission to redistribute with modification. Would creating a Bioconda recipe which takes the gtz binary and throws away the `lib` directory that comes packaged with it, and instead installs python 2.7 through Conda be considered modification and thus not be permitted?

**Comment by superligen** [comment]
Hi,   We are glad to permit to integrate the GTZ program into Bioconda. We have changed the license : " without modification are permitted"  --> "only without modification of gtz binary program are permitted". That may allow you to package GTZ program enough.   Anything we can help, please contact me.  gen.li@genetalks.com   After the Spring festival, we will update GTZ to v1.0, and will release windows, linux, macosx version. We'll let you know by then.   Happy China Spring festival !   Genetalks   Gen Li      ------------------------------------------------------------------发件人：Matthew Spelchak <notifications@github.com>发送时间：2018年2月15日(星期四) 22:47收件人：Genetalks/gtz <gtz@noreply.github.com>抄　送：Subscribed <subscribed@noreply.github.com>主　题：[Genetalks/gtz] Permitted to create Bioconda recipe? (#4)
Hello, I'm interested in creating a Bioconda recipe for GTZ, but I can't quite tell if the license permits this.I noticed the license is very similar to a BSD-2 license, just without the permission to redistribute with modification. Would creating a Bioconda recipe which takes the gtz binary and throws away the lib directory that comes packaged with it, and instead installs python 2.7 through Conda be considered modification and thus not be permitted?—

**Comment by tizzir** [comment]
Thank you @superligen for the quick response and solution!
