### ISSUE TITLE
gtz_public_0.2.2k 能用于生产环境吗？

### ISSUE THREAD

**Issue by shenweiyan** [Genetalks/gtz#5]
http://gtz.io/gtz_public_0.2.2k_centos_release.tgz
http://gtz.io/gtz_public_0.2.2k_ubuntu_release.tgz

请问以上两个版本的 gtz 可以用于 Hiseq2500、Hiseq3000、Xten 生产环境的数据吗？

**Comment by dengnan26567** [comment]
1、我们发布的public gtx.zip(简称gtz)工具是作为学习研究以及行业交流存在的，虽然会经过大量的数据测试，但是官方并不保证public版本100%的稳定性、高保真性；
2、如果您对数据处理的稳定性、高保真性要求非常高，需要用于商业用途的话，建议您使用我们的enterprise gtx.zip也就是企业版本，现在已经在云上免费体验了，地址为：http://gtz.io。
enterprise 版在压缩性能上也是优于public版本的，用enterprise压缩的fastq文件可以降到public版本的一半大小，为源文件的2.6%左右。
3、您有任何问题可以24小时致电我们的市场人员：18611833657（易经理），我们可以提供免费的技术咨询。

**Comment by dengnan26567** [comment]
1、我们发布的public gtx.zip(简称gtz)工具是作为学习研究以及行业交流存在的，虽然会经过大量的数据测试，但是官方并不保证public版本100%的稳定性、数据一致性；
2、如果您对数据处理的稳定性、数据一致性要求非常高，需要用于商业用途的话，建议您使用我们的enterprise gtx.zip也就是企业版本，现在已经在云上免费体验了，地址为：http://gtz.io。
enterprise 版在压缩率上也是优于public版本的，用enterprise压缩的fastq文件可以降到public版本的一半大小，为源文件的2.6%左右。
3、您有任何问题可以24小时致电我们的市场人员：18611833657（易经理），我们可以提供免费的技术咨询。

**Comment by dengnan26567** [comment]
您好，
这两个版本的GTZ是可以处理这几个测序设备的fastq数据的，跟设备型号无关，只要是fastq格式的数据我们都可以压缩

**Comment by dengnan26567** [comment]
同时需要阐述的是：
1、我们发布的 GTX.Zip Public版本(简称gtz)工具是仅作为学习研究以及行业交流存在。但即便是这个目的，Public版本的GTZ 也是通过了严苛的PB级数据测试，可以放心使用；
2、若要应对生产环境的数据，我们非常建议您使用我们的 GTX.Zip Enterprise企业版本。企业版本采用更高倍率的压缩技术，在压缩大小上，上几乎可以降到Public版本的一半，gz数据的1/6大小。此外，重要的是企业版本采用业内唯一的企业级数据正确性与安全策略。在压缩的过程中，并行地进行解压还原测试。只有确认解压还原测试后的数据与源数据完全一致，压缩数据才会落地。从原理上保证压缩后的数据100%准确无损还原。
3、企业版本分线上和线下版本，线上版本现在可以在云上免费体验了，地址为：http://gtz.io。线下的GTX.Zip Enterprise版本，可以联系我们的市场经理：18611833657（易经理），我们可以提供相关的咨询和部署服务。
4. 即便是  GTZ Public版本，有任何问题，我们都提供24小时技术支持服务。
