### ISSUE TITLE
how to use standard input?

### ISSUE THREAD

**Issue by ThomasChen2016** [Genetalks/gtz#7]
I tried following code, but it didn't work

`zcat sample_*_R1_*.fastq.gz | ./gtz -o sample_R1.fastq.gtz `

output:
```
Powered by GTXLab of Genetalks. (built in PUBLIC-1.0-V-2018-08-06 02:48:41 )
Compressor initializing ... 
nothing to compress.
```

**Comment by superligen** [comment]
Sorry for late. Now, gtz can input gz file directly, the new GTX.Zip Prefessional does not support to use standard input stream as input source. We will support this feature in the next version.

**Comment by ruanjue** [comment]
Hi Li Gen,

I think it is ultra useful to support read from STDIN and output to STDOUT, Expecting a nice update!

Best,
Jue

**Comment by superligen** [comment]
Hi, 
    Now, decompressing to stdout is supported, download the latest GTZ, and enjoy.

**Comment by ruanjue** [comment]
Nice!
